name: sampke demo github action app

on:
    push:
        branches:
            - main

jobs:
    buildanddeploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: action/checkout@v2

        - name: Setup docker buildx
          uses: docker/setup-buildx-action@v2

        - name: Cache docker layers
          uses: action/cache@v2
          with:
            path: /tmp/.buildx-cache
            key: ${{runner.os}}-buildx-

        - name: Build Docker image
          run: |
            docker build -t my-docker-repo/my-app:${{github.sha}} .
        
        - name: login to docker hub
          uses: docker/login-action@v2
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}

        - name: push docker image
          run: |
            docker push my-docker-repo/my-app:${{github.sha}}

